%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/yashtambi/Documents/TUD/Academics/Q2/CH3212_StorageTechnology/MATLAB2/RegionData.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/12/13 16:36:39

function [regiondata] = getregiondata(filename)
%% Import the data
[~, ~, raw] = xlsread(filename,'Sheet1');
raw = raw(2:end,:);
stringVectors = string(raw(:,1));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[2,3]);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
regiondata = table;

%% Allocate imported array to column variable names
regiondata.State = cellstr(stringVectors(:,1));
regiondata.Latitude = data(:,1);
regiondata.Longitude = data(:,2);

%% Clear temporary variables
clearvars data raw stringVectors;
end