function [PShydro,PShydroM,EHSyear,AHA,CHA] = FUNsupplyHYDRO(Pdemand, Psupply, r)

%% Constants
% time
tpd = 96;
td = 365;
tpy = td*tpd;
tdy = 1:1:td;
tsy = 1:1:tpy;
t=1:35040;



%% Rain profile per Region
% 2 profiles: profile aaa is less rain in the summer (region 1 and 3), profile bbb is more rain in the summer (region 2,4 and 5)

a1 = 0.3;       %range
a2 = 0.45;       %average
a3 = 3  ;        %3 is positive 1 is negative

b1 = 0.3;       %range
b2 = 0.45;       %average
b3 = 1  ;        %3 is positive 1 is negative


aaa = a1*sin((2*pi*(tsy+a3*(tpy/4)))/tpy)+a2;
bbb = b1*sin((2*pi*(tsy+b3*(tpy/4)))/tpy)+b2;

RainM = zeros(5,tpy);

for j = 1:tpy
    RainM(1,j) = bbb(j);
end

for j = 1:tpy
    RainM(2,j) = aaa(j);
end

for j = 1:tpy
    RainM(3,j) = bbb(j);
end

for j = 1:tpy
    RainM(4,j) = aaa(j);
end

for j = 1:tpy
    RainM(5,j) = aaa(j);
end

clear a1 a2 a3 b1 b2 b3 aaa bbb

%% Hydro electricity per region

%Hydro data /Region/Potential capacity(MW) /Potential Annual
%Generation(MWh) /Capacity factor
HYDROdata = xlsread('HYDRO.xlsx',2,'C2:F38');

idx=HYDROdata(1:37,1)==r;
HYnr = sum(idx(:));
HYDROregion = zeros(HYnr,3);
n=1;

for i = 1:37
    if HYDROdata(i,1) == r           
        HYDROregion(n,1)=HYDROdata(i,2);
        HYDROregion(n,2)=HYDROdata(i,3);
        HYDROregion(n,3)=HYDROdata(i,4);
        n = n + 1;        
    end    
end

%% (TEST) fill up the dam with rain water (without pumped storage or elec generation)
HYDROdamsEt = zeros(HYnr,tpy);
Epot=zeros(HYnr,1);
% Energy in dam [MWh] = j-1 + (Potential annual generation) * (Rain season) * 1/capacity factor
for i = 1:HYnr
    for j = 2:tpy
    HYDROdamsEt(i,j) = HYDROdamsEt(i,j-1) + (HYDROregion(i,2)/tpy) * RainM(r,j) * (1/HYDROregion(i,3));
    end
    Epot(i,1)=HYDROdamsEt(i,tpy);
end

clear HYDROdamsEt

%% (TEST) Excess/deficit
Pexcess  = zeros(1,td*tpd);
Pdeficit = zeros(1,td*tpd);

for j = 2:tpy
    if Pdemand(j) < Psupply(j)
        Pexcess(j) = Psupply(j) - Pdemand(j);
    else
        Pdeficit(j) = Pdemand(j) - Psupply(j);
    end
end

%% SORT HYDROREGION
HYDROregion = sortrows(HYDROregion,'descend');

%% Energy in Hydroplants 
%TODO's 

%energy in HYDROplant
HYDROdamsE = zeros(HYnr,tpy);
%power generated by hydroplant
Phydrodam  = zeros(HYnr,tpy);
%energy in dam january first
for i = 1:HYnr
    HYDROdamsE(i,1) = 0.0025*HYDROregion(i,2);
end

%NEW supply HYDRO
PHenPV =     zeros(HYnr+1,td*tpd);

%excess/deficit
PHexcess  = zeros(HYnr+1,td*tpd);
PHdeficit = zeros(HYnr+1,td*tpd);

%First line of Excess/deficit
for j = 2:tpy        
    if Pdemand(j) < Psupply(j)
        PHexcess(1,j) = Psupply(j) - Pdemand(j);
    else
        PHdeficit(1,j) = Pdemand(j) - Psupply(j);
    end
end

%all hydroplants
for i = 1:HYnr
    for j = 2:tpy

        %HYDROPLANT
        HYDROdamsE(i,j) = HYDROdamsE(i,j-1) + (HYDROregion(i,2)/(tpy)) * RainM(r,j) * (1/HYDROregion(i,3));
            
        %If the lake is empty
        if HYDROdamsE(i,j-1) < 1*HYDROregion(i,1)
            %pumped storage
            if PHexcess(i,j) > 0
                HYDROdamsE(i,j) = HYDROdamsE(i,j-1) + 0.25*0.8*HYDROregion(i,1) + (HYDROregion(i,2)/(tpy)) * RainM(r,j) * (1/HYDROregion(i,3));
                Phydrodam(i,j)  = -0.8*HYDROregion(i,1);
            else
            end
          
        %If the lake is between min and max volume
        elseif HYDROdamsE(i,j-1) < 0.005*HYDROregion(i,2)
            if PHdeficit(i,j) > 0 && PHdeficit(i,j) > HYDROregion(i,1)
                HYDROdamsE(i,j) = HYDROdamsE(i,j-1)-0.25*HYDROregion(i,1);
                Phydrodam(i,j)  = HYDROregion(i,1);
            %pumped storage
            elseif PHexcess(i,j) > 0
                HYDROdamsE(i,j) = HYDROdamsE(i,j-1) + 0.25*0.8*HYDROregion(i,1) + (HYDROregion(i,2)/(tpy)) * RainM(r,j) * (1/HYDROregion(i,3));
                Phydrodam(i,j)  = -0.8*HYDROregion(i,1);
            end
            
        %If the lake is above max volume
        else
            if PHdeficit(i,j) > 0 && PHdeficit(i,j) > HYDROregion(i,1)
                HYDROdamsE(i,j) = HYDROdamsE(i,j-1)-0.25*HYDROregion(i,1);
                Phydrodam(i,j)  = HYDROregion(i,1);
            else
                HYDROdamsE(i,j) = HYDROdamsE(i,j-1);
            end
        end
        
            %create new Excess/deficit
            PHenPV(i+1,j) = PHenPV(i,j)+Phydrodam(i,j) ;
            if Pdemand(j) < (Psupply(j) + PHenPV(i,j))
                PHexcess(i+1,j) = (Psupply(j) + PHenPV(i+1,j)) - Pdemand(j);
                if PHexcess(i+1,j) < 0
                    PHexcess(i+1,j) = 0;
                end
            else
                PHdeficit(i+1,j) = Pdemand(j) - (Psupply(j) + PHenPV(i+1,j));
                if PHdeficit(i+1,j) < 0
                    PHdeficit(i+1,j) = 0; 
                end
            end   
            
    end
end

%% smoothen powercurve
PShydro = smooth(PHenPV(HYnr+1,1:tpy));
PShydro = smooth(PShydro);

%% split powercurve
PShydrop = zeros(1,tpy);
for i = 1:tpy
    if PShydro(i) < 0
        PShydrop(1,i) = 0;
    else
        PShydrop(1,i) = PShydro(i);
    end
end
        
%% Create year matrix
PShydroM = zeros(365,96);
for i = 1:365
    for j = 1:96
        PShydroM(i,j) = PShydro(j+((i-1)*96));
    end
end


EHSyear = trapz(0.25*PShydrop);

%% Costs
%energy per region
SE = sum(HYDROregion);
%(average area needed per region km2)
AHA = (SE(2)) * 0.001205256; 
%(average cost per region)
CHA = (SE(1) * ((1000000+3500000)/2));

%% clear data

clear EDRdS EDRdW EDRy f i j idx lpf n PV area PVtotalIrr PVtotOut r t RainM

%% plot
%{
%window
figure('Name','Supply Hydro')
set(gcf, 'Position', [100, 100, 1100, 600])

subplot(2,2,1)
for i = 1:HYnr
    plot(HYDROdamsE(i,1:tpy))
    hold on
end
    
xticks([1 tpy/4 tpy/2 (3*tpy)/4 tpy])
xticklabels({'January','March','June','September','December'})
title('Energy in Hydroplant')
xlabel('Year 2050')
ylabel('MWh')
hold on

subplot(2,2,3)
plot(Pdeficit(1,180*96:181*96),'b')
hold on
plot(PHdeficit(HYnr+1,180*96:181*96),'r')
xticks([1 tpy/4 tpy/2 (3*tpy)/4 tpy])
xticklabels({'January','March','June','September','December'})
title('deficit, excess (180th day)')
xlabel('Year 2050')
ylabel('MWh')
hold on

subplot(2,2,2)
plot(PHenPV(HYnr+1,1:tpy)) 
hold on
plot(PShydro(1:tpy),'r')  
xticks([1 tpy/4 tpy/2 (3*tpy)/4 tpy])
xticklabels({'January','March','June','September','December'})
title('P hydro per region (180th day)')
xlabel('Year 2050')
ylabel('MW')
hold on

subplot(2,2,4)
for i = 1:HYnr
    plot(HYDROdamsE(i,180*96:181*96))
    hold on
end
    
xticks([1 tpy/4 tpy/2 (3*tpy)/4 tpy])
xticklabels({'January','March','June','September','December'})
title('Energy in Hydroplant (180th day)')
xlabel('Year 2050')
ylabel('MWh')
hold on


%}