%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/yashtambi/Documents/TUD/Academics/Q2/CH3212_StorageTechnology/Model/biomass/Biomass.xlsx
%    Worksheet: Sheet2
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/01/07 20:06:22

%% Import the data
[~, ~, raw] = xlsread('/Users/yashtambi/Documents/TUD/Academics/Q2/CH3212_StorageTechnology/Model/biomass/Biomass.xlsx','Sheet2');
raw = raw(2:end,:);
stringVectors = string(raw(:,1));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[2,3,4,5,6,7]);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
biomassdata = table;

%% Allocate imported array to column variable names
biomassdata.Crop = cellstr(stringVectors(:,1));
biomassdata.Region = data(:,1);
biomassdata.Plantingtime = data(:,2);
biomassdata.Harvestingtime = data(:,3);
biomassdata.Photosyntheticefficiency = data(:,4);
biomassdata.Massratiokgproductkgplant = data(:,5);
biomassdata.Ouputinputratiokgkg = data(:,6);

%% Clear temporary variables
clearvars data raw stringVectors;